// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type Tag = {
  tagId: string,
  gameId: string,
  isActive: boolean,
  orderIndex: number,
  clue: string | undefined,
  lat: number | undefined,
  lon: number | undefined,
  accuracyM: number | undefined,
  activatedBy: string | undefined,
  activatedAt: bigint | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Tag {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("tagId", AlgebraicType.createStringType()),
      new ProductTypeElement("gameId", AlgebraicType.createStringType()),
      new ProductTypeElement("isActive", AlgebraicType.createBoolType()),
      new ProductTypeElement("orderIndex", AlgebraicType.createI32Type()),
      new ProductTypeElement("clue", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("lat", AlgebraicType.createOptionType(AlgebraicType.createF64Type())),
      new ProductTypeElement("lon", AlgebraicType.createOptionType(AlgebraicType.createF64Type())),
      new ProductTypeElement("accuracyM", AlgebraicType.createOptionType(AlgebraicType.createI32Type())),
      new ProductTypeElement("activatedBy", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("activatedAt", AlgebraicType.createOptionType(AlgebraicType.createI64Type())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Tag): void {
    Tag.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Tag {
    return Tag.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


