// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

export type ActivateTagWithLocation = {
  gameId: string,
  tagId: string,
  lat: number,
  lon: number,
  accuracyM: number,
  activatedBy: string,
  orderIndex: number,
  clue: string | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ActivateTagWithLocation {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("gameId", AlgebraicType.createStringType()),
      new ProductTypeElement("tagId", AlgebraicType.createStringType()),
      new ProductTypeElement("lat", AlgebraicType.createF64Type()),
      new ProductTypeElement("lon", AlgebraicType.createF64Type()),
      new ProductTypeElement("accuracyM", AlgebraicType.createI32Type()),
      new ProductTypeElement("activatedBy", AlgebraicType.createStringType()),
      new ProductTypeElement("orderIndex", AlgebraicType.createI32Type()),
      new ProductTypeElement("clue", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ActivateTagWithLocation): void {
    ActivateTagWithLocation.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ActivateTagWithLocation {
    return ActivateTagWithLocation.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

